.TH "dot_mcp" "1" 
.SH "NAME" 
dot_mcp \(em  mcp for s3d  
.SH "SYNOPSIS" 
.PP 
\fBdot_mcp\fR [\-\-s3d-url \fIurl\fR]  
.SH "OPTIONS" 
.PP 
This program follows the usual GNU command line syntax. A summary of 
the options supported by \fBdot_mcp\fR is below. 
 
.IP "\fB\-\-s3d-url \fIurl\fR\fP" 10 
skip S3D environment and connect to this url  
.SH "DESCRIPTION" 
.PP 
\fBdot_mcp(1)\fR is a mcp (which is the window manager in s3d-terms) for s3d. 
 
.PP 
 
.SH "SEE ALSO" 
.PP 
\fBs3d\fR(1). 
.PP 
\fI s3d project page on berlios  (link to URL http://s3d.berlios.de/) \fR  
.\" created by instant / docbook-to-man, Fri 29 Aug 2008, 18:39 
