.TH "kism3d" "1" 
.SH "NAME" 
kism3d \(em  802.11 visualizer for s3d  
.SH "SYNOPSIS" 
.PP 
\fBkism3d\fR [\-\-s3d-url \fIurl\fR] \fIHOST\fR:\fIPORT\fR  
.SH "DESCRIPTION" 
.PP 
\fBkism3d(1)\fR is a 3D 802.11 visualizer for kismet. 
 
.PP 
 
.SH "OPTIONS" 
.PP 
 
This program follows the usual GNU command line syntax. A summary of 
the options supported by \fBkism3d\fR is below. 
 
.IP "\fB\-\-s3d-url \fIurl\fR\fP" 10 
skip S3D environment and connect to this url  
.SH "SEE ALSO" 
.PP 
\fBs3d\fR(1), \fBkismet\fR(1). 
.PP 
\fI s3d project page on berlios  (link to URL http://s3d.berlios.de/) \fR  
.\" created by instant / docbook-to-man, Fri 29 Aug 2008, 18:39 
