.TH "s3d" "1" 
.SH "NAME" 
s3d \(em  network display server  
.SH "SYNOPSIS" 
.PP 
\fBs3d\fR [\-s|\-\-use-sdl]  [\-r|\-\-rc \fIrc-script\fR]  [\-n|\-\-no-rc]  
.SH "DESCRIPTION" 
.PP 
\fBs3d(1)\fR is a network display server which can be used as 3d desktop environment. 
 
.PP 
 
.SH "OPTIONS" 
.PP 
 
This program follows the usual GNU command line syntax. A summary of 
the options supported by \fBs3d\fR is below. 
 
.IP "\fB-s\fP, \fB\-\-use-sdl\fP" 10 
Tells s3d to use SDL as graphics framework system.  
.IP "\fB-r \fIrc-script\fR\fP, \fB\-\-rc \fIrc-script\fR\fP" 10 
Use the specified file as rc-script. By default s3d uses ~/.s3drc as 
per-user rc-script and /etc/s3drc as system-wide rc-script 
.IP "\fB-n\fP, \fB\-\-no-rc\fP" 10 
Don't use rc-scripts even if the exist in the apropriate locations.  
.SH "SEE ALSO" 
.PP 
\fI s3d project page on berlios  (link to URL http://s3d.berlios.de/) \fR  
.SH "AUTHOR" 
.PP 
This manual page was written by Timo Schneider timo.schneider@s2004.tu-chemnitz.de  
for the \fBDebian\fP project (but may be used by others). 
 
.\" created by instant / docbook-to-man, Fri 29 Aug 2008, 18:39 
