.TH "s3d_x11gate" "1" 
.SH "NAME" 
s3d_x11gate \(em  3d gateway for x11 desktops  
.SH "SYNOPSIS" 
.PP 
\fBs3d_x11gate\fR [\-h|\-\-help]  [\-\-s3d-url \fIurl\fR]  
.SH "DESCRIPTION" 
.PP 
\fBs3d_x11gate(1)\fR is a 3D gateway for x11 desktops. 
 
.PP 
 
.SH "OPTIONS" 
.PP 
This program follows the usual GNU command line syntax. A summary of 
the options supported by \fBs3d_x11gate\fR is below. 
 
.IP "\fB-h\fP, \fB\-\-help\fP 				" 10 
Show summary of options and exit.  
.IP "\fB\-\-s3d-url \fIurl\fR\fP" 10 
skip S3D environment and connect to this url  
.SH "SEE ALSO" 
.PP 
\fBs3d\fR(1). 
.PP 
\fI s3d project page on berlios  (link to URL http://s3d.berlios.de/) \fR  
.\" created by instant / docbook-to-man, Fri 29 Aug 2008, 18:39 
