.TH "s3dosm" "1" 
.SH "NAME" 
s3dosm \(em  gps card application for s3d  
.SH "SYNOPSIS" 
.PP 
\fBs3dosm\fR [\-o|\-\-osm \fIMINLAT\fR,\fIMINLON\fR,\fIMAXLAT\fR,\fIMAXLON\fR]  [\-h|\-\-help]  [\-\-s3d-url \fIurl\fR]  [\fIfiles\fR]  
.SH "DESCRIPTION" 
.PP 
\fBs3dosm(1)\fR is a 3D gps card application for openstreetmap/kismet xml card data. 
 
.PP 
 
.SH "OPTIONS" 
.PP 
This program follows the usual GNU command line syntax. A summary of 
the options supported by \fBs3dosm\fR is below. 
 
.IP "\fB-h\fP, \fB\-\-help\fP 				" 10 
Show summary of options and exit.  
.IP "\fB-o\fP, \fB\-\-osm\fP \fIMINLAT\fR,\fIMINLON\fR,\fIMAXLAT\fR,\fIMAXLON\fR 				" 10 
Load a map with the given bounding box from the openstreetmap server.  
.IP "\fB\-\-s3d-url \fIurl\fR\fP" 10 
skip S3D environment and connect to this url  
.SH "EXAMPLES" 
.PP 
 
.PP 
.nf 
$  
.ft B 
s3osm \-\-osm \fI12.90142,50.82475,12.93352,50.84592\fR 
.ft  
$  
.ft B 
s3osm \fIosmdata\fR.xml 
.ft 
.fi 
 
 
.SH "SEE ALSO" 
.PP 
\fBs3d\fR(1). 
.PP 
\fI s3d project page on berlios  (link to URL http://s3d.berlios.de/) \fR  
.\" created by instant / docbook-to-man, Fri 29 Aug 2008, 18:58 
