#ifndef _CONFIG_H_
#define _CONFIG_H_

/* config.h.  Generated by cmake from config.h.cmake */

#cmakedefine G_SDL 1
#cmakedefine HAVE_GPS 1
#cmakedefine HAVE_GPS_NEW 1
#cmakedefine SHM 1
#cmakedefine SIGS 1
#cmakedefine TCP 1

/* path where to find objects */
#cmakedefine OBJECTPATH "${OBJECTPATH}"

/* set debug level (can be changed by -DDEBUG=vlow|low|med|high|vhigh )*/
#cmakedefine DEBUG ${DEBUG_LEVEL}

#cmakedefine UNUSEDPARAM_ATTRIBUTE 1
#cmakedefine UNUSEDPARAM_OMIT 1

#endif /* _CONFIG_H_ */
