#ifndef _CONFIG_H_
#define _CONFIG_H_

/* config.h.  Generated by cmake from config.h.cmake */

#cmakedefine G_SDL 1
#cmakedefine HAVE_GPS 1
#cmakedefine SHM 1
#cmakedefine SIGS 1
#cmakedefine TCP 1

/* path where to find objects */
#cmakedefine OBJECTPATH "${OBJECTPATH}"

/* set debug level (can be changed by -DDEBUG=vlow|low|med|high|vhigh )*/
#cmakedefine DEBUG ${DEBUG_LEVEL}

#cmakedefine UNUSEDPARAM_ATTRIBUTE 1
#cmakedefine UNUSEDPARAM_OMIT 1

#cmakedefine BIN_INSTALL_DIR "${BIN_INSTALL_DIR}"
#cmakedefine CFG_INSTALL_DIR "${CFG_INSTALL_DIR}"
#cmakedefine LIB_INSTALL_DIR "${LIB_INSTALL_DIR}"
#cmakedefine INCLUDE_INSTALL_DIR "${INCLUDE_INSTALL_DIR}"
#cmakedefine DATA_INSTALL_DIR "${DATA_INSTALL_DIR}"
#cmakedefine HTML_INSTALL_DIR "${HTML_INSTALL_DIR}"
#cmakedefine MAN_INSTALL_DIR "${MAN_INSTALL_DIR}"
#cmakedefine PKGCFG_INSTALL_DIR "${PKGCFG_INSTALL_DIR}"

#endif /* _CONFIG_H_ */
