.\"     Title: s3d_load_polygon_tex_coords
.\"    Author:
.\" Generator: DocBook XSL Stylesheets
.\"
.\"    Manual:
.\"    Source:
.\"
.TH "S3D_LOAD_POLYGON_TEX" "3" "" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
s3d_load_polygon_tex_coords \- add texture coordinates to polygons
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <s3d\&.h>
.fi
.ft
.HP 32
.BI "int s3d_load_polygon_tex_coords(int\ " "object" ", const\ float\ *" "tbuf" ", uint32_t\ " "start" ", uint16_t\ " "n" ");"
.SH "DESCRIPTION"
.PP
Just as s3d_pep_polygon_tex_coords(), with the difference you won\'t alter the latest n polygons but n polygons starting with index start\&.
