.TH "s3d_pop_texture" "3" 
.SH "NAME" 
s3d_pop_texture \(em  
.SH "SYNOPSIS" 
.PP 
.nf 
#include <s3d.h> 
.sp 1 
\fBint \fBs3d_pop_texture\fP\fR( 
\fB	int \fBobject\fR\fR, 
\fB	uint32_t \fBn\fR\fR); 
.fi 
.SH "Description" 
.PP 
Deletes the latest n textures from the texture stack of the object.          
.\" created by instant / docbook-to-man, Mon 01 Sep 2008, 20:31 
