.TH "s3d_pep_polygon_tex_coords" "3" 
.SH "NAME" 
s3d_pep_polygon_tex_coords \(em add texture coordinates to polygons 
.SH "SYNOPSIS" 
.PP 
.nf 
#include <s3d.h> 
.sp 1 
\fBint \fBs3d_pep_polygon_tex_coords\fP\fR( 
\fB	int \fBobject\fR\fR, 
\fB	const float *\fBtbuf\fR\fR, 
\fB	uint16_t \fBn\fR\fR); 
.fi 
.SH "Description" 
.PP 
Pimp the latest n polygons with texture coordinates. tbuf has 6*n float values for its entries, which are supplied in the order as in s3d_pep_polygon_tex_coord()          
.\" created by instant / docbook-to-man
