.TH "s3d_import_model_file" "3" 
.SH "NAME" 
s3d_import_model_file \(em read model from file 
.SH "SYNOPSIS" 
.PP 
.nf 
#include <s3d.h> 
.sp 1 
\fBint \fBs3d_import_model_file\fP\fR( 
\fB	const char *\fBfname\fR\fR); 
.fi 
.SH "Description" 
.PP 
Imports an 3d object file and returns the object number. Quite a number of formats are supported, like 3D Studio (.3ds, .prj), Lightwave (.lw, .lwb, .lwo), Quake Models (.md3), or simply everything libg3d supports. :) 
.PP 
.RS 
\fBWarning:   
.PP 
Of course, you won't forget to toggle it visible, won't you?  
 
.RE 
.\" created by instant / docbook-to-man
