.TH "s3d_pep_material_a" "3" 
.SH "NAME" 
s3d_pep_material_a \(em rewrite material with alpha 
.SH "SYNOPSIS" 
.PP 
.nf 
#include <s3d.h> 
.sp 1 
\fBint \fBs3d_pep_material_a\fP\fR( 
\fB	int \fBobject\fR\fR, 
\fB	float \fBamb_r\fR\fR, 
\fB	float \fBamb_g\fR\fR, 
\fB	float \fBamb_b\fR\fR, 
\fB	float \fBamb_a\fR\fR, 
\fB	float \fBspec_r\fR\fR, 
\fB	float \fBspec_g\fR\fR, 
\fB	float \fBspec_b\fR\fR, 
\fB	float \fBspec_a\fR\fR, 
\fB	float \fBdiff_r\fR\fR, 
\fB	float \fBdiff_g\fR\fR, 
\fB	float \fBdiff_b\fR\fR, 
\fB	float \fBdiff_a\fR\fR); 
.fi 
.SH "Description" 
.PP 
Overwriting the latest pushed Material, overwriting the current value with the specified one, with alpha value in contrast to s3d_pep_material See s3d_push_materials_a if you want to pep more materials.          
.\" created by instant / docbook-to-man
