.\"     Title: s3d_link
.\"    Author:
.\" Generator: DocBook XSL Stylesheets
.\"
.\"    Manual:
.\"    Source:
.\"
.TH "S3D_LINK" "3" "" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
s3d_link \- link object to another one
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <s3d\&.h>
.fi
.ft
.HP 13
.BI "int s3d_link(int\ " "oid_from" ", int\ " "oid_to" ");"
.SH "DESCRIPTION"
.PP
A linked object will move along with it\'s link parent\&. For example if you have a book on a table, you can link the book to the table so the book will "keep on the table" if you move the table around in space\&. It will also rotate with the table etc\&.
