'\" t
.\"     Title: s3d_push_material
.\"    Author: Simon Wunderlich
.\" Generator: DocBook XSL Stylesheets
.\"
.\"    Manual: s3d Manual
.\"    Source: s3d
.\"  Language: English
.\"
.TH "S3D_PUSH_MATERIAL" "3" "" "s3d" "s3d Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
s3d_push_material \- push material
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <s3d\&.h>
.fi
.ft
.HP \w'int\ s3d_push_material('u
.BI "int s3d_push_material(int\ " "object" ", float\ " "amb_r" ", float\ " "amb_g" ", float\ " "amb_b" ", float\ " "spec_r" ", float\ " "spec_g" ", float\ " "spec_b" ", float\ " "diff_r" ", float\ " "diff_g" ", float\ " "diff_b" ");"
.SH "DESCRIPTION"
.PP
Pushes a material for an object\&. you will have to count them yourself too, as polygons will ask for the material index number\&. The material properties are given in rgb (red/green/blue) color codes, in float\&. 0\&.0 is the minimum, 1\&.0 is the maximum a color value can be\&. The specular color is the color which is directly reflected from the light source\&. The diffuse color is the color which can be seen in the bright side of the object, and the ambience color is the color of the shadow side of the object\&.
.SH "AUTHOR"
.PP
\fBSimon Wunderlich\fR
.RS 4
Author of s3d
.RE
