'\" t
.\"     Title: s3d_vector_angle
.\"    Author: Simon Wunderlich
.\" Generator: DocBook XSL Stylesheets
.\"
.\"    Manual: s3d Manual
.\"    Source: s3d
.\"  Language: English
.\"
.TH "S3D_VECTOR_ANGLE" "3" "" "s3d" "s3d Manual"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
s3d_vector_angle \- calculate angle between two vectors
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <s3d\&.h>
.fi
.ft
.HP \w'float\ s3d_vector_angle('u
.BI "float s3d_vector_angle(const\ float\ " "vector1" "[], const\ float\ " "vector2" "[]);"
.SH "DESCRIPTION"
.PP
Calculates and returns the angle between vector1 and vector2\&. Please note that the resulting angle is between 0 and PI, therefore not covering the whole period! To convert in degrees just do result*180/M_PI\&. All vectors should have the format float[3]\&. More info on wikipedia\&. http://en\&.wikipedia\&.org/wiki/Vector_(spatial)
.SH "AUTHOR"
.PP
\fBSimon Wunderlich\fR
.RS 4
Author of s3d
.RE
