.TH "s3d_load_texture" "3" 
.SH "NAME" 
s3d_load_texture \(em load texture from memory 
.SH "SYNOPSIS" 
.PP 
.nf 
#include <s3d.h> 
.sp 1 
\fBint \fBs3d_load_texture\fP\fR( 
\fB	int \fBobject\fR\fR, 
\fB	uint32_t \fBtex\fR\fR, 
\fB	uint16_t \fBxpos\fR\fR, 
\fB	uint16_t \fBypos\fR\fR, 
\fB	uint16_t \fBw\fR\fR, 
\fB	uint16_t \fBh\fR\fR, 
\fB	const uint8_t *\fBdata\fR\fR); 
.fi 
.SH "Description" 
.PP 
This will load an 32bit rgba image supplied in data at position xpos,ypos of the texture tex. The image has the width w and height h. This can be used to update only parts of the texture. It's no problem to supply big textures, as the image will be sent to server in fragments. Of course, you will have created the texture with s3d_push_texture, have an material assigned to the texture with s3d_pep_material_texture() and have your polygons set sane polygon texture coords using s3d_pep_polygon_tex_coord().          
.\" created by instant / docbook-to-man
