.\"     Title: s3d_pep_vertices
.\"    Author:
.\" Generator: DocBook XSL Stylesheets
.\"
.\"    Manual:
.\"    Source:
.\"
.TH "S3D_PEP_VERTICES" "3" "" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
s3d_pep_vertices \- rewrite lines
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <s3d\&.h>
.fi
.ft
.HP 21
.BI "int s3d_pep_vertices(int\ " "object" ", const\ float\ *" "vbuf" ", uint16_t\ " "n" ");"
.SH "DESCRIPTION"
.PP
Alter the latest n pushed vertex\&. vbuf holds the values which are used to overwrite the old data, n entries with each 3 floats specifying x,y,z of the vertices\&.
