.\"     Title: s3d_vector_length
.\"    Author:
.\" Generator: DocBook XSL Stylesheets
.\"
.\"    Manual:
.\"    Source:
.\"
.TH "S3D_VECTOR_LENGTH" "3" "" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
s3d_vector_length \- calculate length of vector
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <s3d\&.h>
.fi
.ft
.HP 24
.BI "float s3d_vector_length(const\ float\ " "vector" "[]);"
.SH "DESCRIPTION"
.PP
Calculates and returns the length of the given vector (which should be of the type float[3])\&. More info on wikipedia http://en\&.wikipedia\&.org/wiki/Vector_(spatial)
