.TH "s3d_vector_subtract" "3" 
.SH "NAME" 
s3d_vector_subtract \(em substract two vectors 
.SH "SYNOPSIS" 
.PP 
.nf 
#include <s3d.h> 
.sp 1 
\fBvoid \fBs3d_vector_subtract\fP\fR( 
\fB	const float \fBvector1\fR[]\fR, 
\fB	const float \fBvector2\fR[]\fR, 
\fB	float \fBresult_vector\fR[]\fR); 
.fi 
.SH "Description" 
.PP 
Subtracts vector1 from vector2, writing result into result_vector. All vectors should have the format float[3]. More info on wikipedia. http://en.wikipedia.org/wiki/Vector_(spatial)          
.\" created by instant / docbook-to-man
