.\"     Title: s3d_set_callback
.\"    Author:
.\" Generator: DocBook XSL Stylesheets
.\"
.\"    Manual:
.\"    Source:
.\"
.TH "S3D_SET_CALLBACK" "3" "" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
s3d_set_callback \- sets a callback
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <s3d\&.h>
.fi
.ft
.HP 22
.BI "void s3d_set_callback(uint8_t\ " "event" ", s3d_cb\ " "func" ");"
.SH "DESCRIPTION"
.PP
Sets a callback for a certain event\&. this is very useful for event\-oriented applications\&. event callbacks will not interrupt each other or the mainloop\&.
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
Warning
.PP
Defining callbacks will only work after calling s3d_init()

.sp
.RS 4
.nf
 #include <inttypes\&.h>

 void obj_click(struct s3d_evt event)
 {
         printf("object id %"PRIu32" got clicked", *((uint32_t *)event\->buf));
 }
 \&.\&.\&.
 s3d_set_callback(S3D_EVENT_NEW_OBJECT, obj_click);
 // this will tell you when a object got clicked
.fi
.RE
