.TH "s3d_init" "3" 
.SH "NAME" 
s3d_init \(em  
.SH "SYNOPSIS" 
.PP 
.nf 
#include <s3d.h> 
.sp 1 
\fBint \fBs3d_init\fP\fR( 
\fB	int *\fBargc\fR\fR, 
\fB	char ***\fBargv\fR\fR, 
\fB	const char *\fBname\fR\fR); 
.fi 
.SH "Description" 
.PP 
This will initialize the s3d-library and the connection to the Server. It will return 0 on success in Server initializion. name specifies the your programs name. 
.PP 
.nf 
int main(char argc, char **argv) 
{ 
if (!s3d_init(&argc, &argv, "Hello world")) 
{ 
... 
s3d_quit(); 
} 
return(0); 
} 
.fi 
.PP 
.\" created by instant / docbook-to-man, Mon 01 Sep 2008, 20:31 
