.TH "s3d_pep_line" "3" 
.SH "NAME" 
s3d_pep_line \(em  
.SH "SYNOPSIS" 
.PP 
.nf 
#include <s3d.h> 
.sp 1 
\fBint \fBs3d_pep_line\fP\fR( 
\fB	int \fBobject\fR\fR, 
\fB	int \fBv1\fR\fR, 
\fB	int \fBv2\fR\fR, 
\fB	int \fBmaterial\fR\fR); 
.fi 
.SH "Description" 
.PP 
Alter the latest pushed line, overwriting with the supplied values.          
.\" created by instant / docbook-to-man
