.TH "s3d_pop_event" "3" 
.SH "NAME" 
s3d_pop_event \(em  
.SH "SYNOPSIS" 
.PP 
.nf 
#include <s3d.h> 
.sp 1 
\fBstruct s3d_evt * \fBs3d_pop_event\fP\fR( 
\fB	void\fR); 
.fi 
.SH "Description" 
.PP 
Pops the latest event from the stack. Don't forget to free() both the event and its buffer! Returns a pointer to struct s3d_evt.          
.\" created by instant / docbook-to-man
