.TH "s3d_vector_length" "3" 
.SH "NAME" 
s3d_vector_length \(em  
.SH "SYNOPSIS" 
.PP 
.nf 
#include <s3d.h> 
.sp 1 
\fBfloat \fBs3d_vector_length\fP\fR( 
\fB	const float \fBvector\fR[]\fR); 
.fi 
.SH "Description" 
.PP 
Calculates and returns the length of the given vector (which should be of the type float[3]). More info on wikipedia http://en.wikipedia.org/wiki/Vector_(spatial)          
.\" created by instant / docbook-to-man
