.TH "s3d_link" "3" 
.SH "NAME" 
s3d_link \(em link object to another one 
.SH "SYNOPSIS" 
.PP 
.nf 
#include <s3d.h> 
.sp 1 
\fBint \fBs3d_link\fP\fR( 
\fB	int \fBoid_from\fR\fR, 
\fB	int \fBoid_to\fR\fR); 
.fi 
.SH "Description" 
.PP 
A linked object will move along with it's link parent. For example if you have a book on a table, you can link the book to the table so the book will "keep on the table" if you move the table around in space. It will also rotate with the table etc.          
.\" created by instant / docbook-to-man
