.\"     Title: s3d_pop_material
.\"    Author:
.\" Generator: DocBook XSL Stylesheets
.\"
.\"    Manual:
.\"    Source:
.\"
.TH "S3D_POP_MATERIAL" "3" "" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
s3d_pop_material \- remove materials
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <s3d\&.h>
.fi
.ft
.HP 21
.BI "int s3d_pop_material(int\ " "object" ", uint32_t\ " "n" ");"
.SH "DESCRIPTION"
.PP
Deletes the latest n material from the material stack of the object\&.
