.TH "s3d_unlink" "3" 
.SH "NAME" 
s3d_unlink \(em removes link from another object 
.SH "SYNOPSIS" 
.PP 
.nf 
#include <s3d.h> 
.sp 1 
\fBint \fBs3d_unlink\fP\fR( 
\fB	int \fBoid\fR\fR); 
.fi 
.SH "Description" 
.PP 
Remove the link of object oid to its target.          
.\" created by instant / docbook-to-man
