.TH "s3d_usage" "3" 
.SH "NAME" 
s3d_usage \(em print s3d parameter 
.SH "SYNOPSIS" 
.PP 
.nf 
#include <s3d.h> 
.sp 1 
\fBvoid \fBs3d_usage\fP\fR(\fBvoid\fR) 
.fi 
.SH "Description" 
.PP 
Prints the possible parameter for the client library (which can be passed in s3d_init())          
.\" created by instant / docbook-to-man
