.\"     Title: s3d_load_line_normals
.\"    Author:
.\" Generator: DocBook XSL Stylesheets
.\"
.\"    Manual:
.\"    Source:
.\"
.TH "S3D_LOAD_LINE_NORMAL" "3" "" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
s3d_load_line_normals \- add normals to line
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <s3d\&.h>
.fi
.ft
.HP 26
.BI "int s3d_load_line_normals(int\ " "object" ", const\ float\ *" "nbuf" ", uint32_t\ " "start" ", uint16_t\ " "n" ");"
.SH "DESCRIPTION"
.PP
Just as s3d_pep_line_normals(), with the difference you won\'t alter the latest n lines but n lines starting with index start\&.
