.TH "s3d_vector_angle" "3" 
.SH "NAME" 
s3d_vector_angle \(em  
.SH "SYNOPSIS" 
.PP 
.nf 
#include <s3d.h> 
.sp 1 
\fBfloat \fBs3d_vector_angle\fP\fR( 
\fB	const float \fBvector1\fR[]\fR, 
\fB	const float \fBvector2\fR[]\fR); 
.fi 
.SH "Description" 
.PP 
Calculates and returns the angle between vector1 and vector2. Please note that the resulting angle is between 0 and PI, therefore not covering the whole period! To convert in degrees just do result*180/M_PI. All vectors should have the format float[3]. More info on wikipedia. http://en.wikipedia.org/wiki/Vector_(spatial)          
.\" created by instant / docbook-to-man, Mon 01 Sep 2008, 20:31 
