.\"     Title: s3d_scale
.\"    Author:
.\" Generator: DocBook XSL Stylesheets
.\"
.\"    Manual:
.\"    Source:
.\"
.TH "S3D_SCALE" "3" "" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
s3d_scale \- scale object
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <s3d\&.h>
.fi
.ft
.HP 14
.BI "int s3d_scale(int\ " "object" ", float\ " "s" ");"
.SH "DESCRIPTION"
.PP
Scales the object\&. about factor s\&. s=1 will be the original size, \-1 will mirror it\&.
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
Warning
.PP
s=0 is forbidden and will be ignored! s3d_scale is also absolute, not relative!

