.TH "s3d_strlen" "3" 
.SH "NAME" 
s3d_strlen \(em  
.SH "SYNOPSIS" 
.PP 
.nf 
#include <s3d.h> 
.sp 1 
\fBfloat \fBs3d_strlen\fP\fR( 
\fB	const char *\fBstr\fR\fR); 
.fi 
.SH "Description" 
.PP 
Returns the length of the string if it were rendered with the currently selected font. That might be useful to estimate the size used for a text and render the background or bounding box before inserting the text.          
.\" created by instant / docbook-to-man, Mon 01 Sep 2008, 20:31 
