.\"     Title: s3d_clear_callback
.\"    Author:
.\" Generator: DocBook XSL Stylesheets
.\"
.\"    Manual:
.\"    Source:
.\"
.TH "S3D_CLEAR_CALLBACK" "3" "" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
s3d_clear_callback \- clears a callback
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <s3d\&.h>
.fi
.ft
.HP 24
.BI "void s3d_clear_callback(uint8_t\ " "event" ");"
.SH "DESCRIPTION"
.PP
Clears the callback which is associated with the event\&.
