.TH "s3d_load_line_normals" "3" 
.SH "NAME" 
s3d_load_line_normals \(em add normals to line 
.SH "SYNOPSIS" 
.PP 
.nf 
#include <s3d.h> 
.sp 1 
\fBint \fBs3d_load_line_normals\fP\fR( 
\fB	int \fBobject\fR\fR, 
\fB	const float *\fBnbuf\fR\fR, 
\fB	uint32_t \fBstart\fR\fR, 
\fB	uint16_t \fBn\fR\fR); 
.fi 
.SH "Description" 
.PP 
Just as s3d_pep_line_normals(), with the difference you won't alter the latest n lines but n lines starting with index start.          
.\" created by instant / docbook-to-man
