.TH "s3d_clone" "3" 
.SH "NAME" 
s3d_clone \(em  
.SH "SYNOPSIS" 
.PP 
.nf 
#include <s3d.h> 
.sp 1 
\fBint \fBs3d_clone\fP\fR( 
\fB	int \fBoid\fR\fR); 
.fi 
.SH "Description" 
.PP 
Clones an already exisiting object. They get just look the same as the parent-object and will change when the parent-object changes. Cloning especially makes sense if you want to use the same object a lot of times. Move and transform is independent from the parent. The function returns the childs object id.          
.\" created by instant / docbook-to-man
