.TH "s3d_angle_to_cam" "3" 
.SH "NAME" 
s3d_angle_to_cam \(em  
.SH "SYNOPSIS" 
.PP 
.nf 
#include <s3d.h> 
.sp 1 
\fBfloat \fBs3d_angle_to_cam\fP\fR( 
\fB	const float \fBobj_pos\fR[]\fR, 
\fB	const float \fBcam_pos\fR[]\fR, 
\fB	float *\fBangle_rad\fR\fR); 
.fi 
.SH "Description" 
.PP 
Given obj_pos and cam_pos in the format float[3], angle_rad about which angle the object should be rotated around the y-axis so that it faces the camera. This might become handy if you have some text floating in space and want it to face the camera. http://en.wikipedia.org/wiki/Vector_(spatial)          
.\" created by instant / docbook-to-man, Mon 01 Sep 2008, 20:31 
