.TH "s3d_quit" "3" 
.SH "NAME" 
s3d_quit \(em shutdown s3d library 
.SH "SYNOPSIS" 
.PP 
.nf 
#include <s3d.h> 
.sp 1 
\fBint \fBs3d_quit\fP\fR( 
\fB	void\fR); 
.fi 
.SH "Description" 
.PP 
closes the connection and cleares the event-stack. it can also be used to leave the s3d_mainloop().          
.\" created by instant / docbook-to-man
