.TH "s3d_clear_callback" "3" 
.SH "NAME" 
s3d_clear_callback \(em  
.SH "SYNOPSIS" 
.PP 
.nf 
#include <s3d.h> 
.sp 1 
\fBvoid \fBs3d_clear_callback\fP\fR( 
\fB	uint8_t \fBevent\fR\fR); 
.fi 
.SH "Description" 
.PP 
Clears the callback which is associated with the event.          
.\" created by instant / docbook-to-man
