.\"     Title: s3d_usage
.\"    Author:
.\" Generator: DocBook XSL Stylesheets
.\"
.\"    Manual:
.\"    Source:
.\"
.TH "S3D_USAGE" "3" "" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
s3d_usage \- print s3d parameter
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <s3d\&.h>
.fi
.ft
.HP 15
.BI "void s3d_usage(void);"
.SH "DESCRIPTION"
.PP
Prints the possible parameter for the client library (which can be passed in s3d_init())
