.TH "s3d_delete_event" "3" 
.SH "NAME" 
s3d_delete_event \(em  
.SH "SYNOPSIS" 
.PP 
.nf 
#include <s3d.h> 
.sp 1 
\fBint \fBs3d_delete_event\fP\fR( 
\fB	const struct s3d_evt *\fBdevt\fR\fR); 
.fi 
.SH "Description" 
.PP 
deletes an event, the argument is the pointer to the event which is to be deleted (maybe obtained from s3d_find_event).          
.\" created by instant / docbook-to-man
