.TH "s3d_push_texture" "3" 
.SH "NAME" 
s3d_push_texture \(em push texture 
.SH "SYNOPSIS" 
.PP 
.nf 
#include <s3d.h> 
.sp 1 
\fBint \fBs3d_push_texture\fP\fR( 
\fB	int \fBobject\fR\fR, 
\fB	uint16_t \fBw\fR\fR, 
\fB	uint16_t \fBh\fR\fR); 
.fi 
.SH "Description" 
.PP 
Adds a new texture with height w and height h on the texturestack.          
.\" created by instant / docbook-to-man
