.TH "s3d_pep_polygon_tex_coord" "3" 
.SH "NAME" 
s3d_pep_polygon_tex_coord \(em add texture coordinates to polygon 
.SH "SYNOPSIS" 
.PP 
.nf 
#include <s3d.h> 
.sp 1 
\fBint \fBs3d_pep_polygon_tex_coord\fP\fR( 
\fB	int \fBobject\fR\fR, 
\fB	float \fBx1\fR\fR, 
\fB	float \fBy1\fR\fR, 
\fB	float \fBx2\fR\fR, 
\fB	float \fBy2\fR\fR, 
\fB	float \fBx3\fR\fR, 
\fB	float \fBy3\fR\fR); 
.fi 
.SH "Description" 
.PP 
Pimp the last polygon pushed with some textures coordinates, x and y values for each vertex point respectively. Those values may be between 0 and 1 and are vertex points on the texture defined in the material of the polygon. If you have more polygons which should get a texture, use s3d_pep_polygon_tex_coords()          
.\" created by instant / docbook-to-man
