'\" t
.\"     Title: s3d_pep_material
.\"    Author: Simon Wunderlich
.\" Generator: DocBook XSL Stylesheets
.\"
.\"    Manual: s3d Manual
.\"    Source: s3d
.\"  Language: English
.\"
.TH "S3D_PEP_MATERIAL" "3" "" "s3d" "s3d Manual"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
s3d_pep_material \- rewrite material
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <s3d\&.h>
.fi
.ft
.HP \w'int\ s3d_pep_material('u
.BI "int s3d_pep_material(int\ " "object" ", float\ " "amb_r" ", float\ " "amb_g" ", float\ " "amb_b" ", float\ " "spec_r" ", float\ " "spec_g" ", float\ " "spec_b" ", float\ " "diff_r" ", float\ " "diff_g" ", float\ " "diff_b" ");"
.SH "DESCRIPTION"
.PP
Overwriting the latest pushed material, overwriting the current value with the specified one\&. See s3d_pep_materials_a if you want to pep more materials\&.
.SH "AUTHOR"
.PP
\fBSimon Wunderlich\fR
.RS 4
Author of s3d
.RE
