.TH "s3d_new_object" "3" 
.SH "NAME" 
s3d_new_object \(em  
.SH "SYNOPSIS" 
.PP 
.nf 
#include <s3d.h> 
.sp 1 
\fBint \fBs3d_new_object\fP\fR( 
\fB	void\fR); 
.fi 
.SH "Description" 
.PP 
Creates a new object, returning the object id. 
.PP 
.RS 
\fBWarning:   
.PP 
Of course, you won't forget to toggle it visible, won't you?  
 
.RE 
.\" created by instant / docbook-to-man
