.\"     Title: s3d_pep_material_texture
.\"    Author:
.\" Generator: DocBook XSL Stylesheets
.\"
.\"    Manual:
.\"    Source:
.\"
.TH "S3D_PEP_MATERIAL_TEX" "3" "" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
s3d_pep_material_texture \- add texture to material
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <s3d\&.h>
.fi
.ft
.HP 29
.BI "int s3d_pep_material_texture(int\ " "object" ", uint32_t\ " "tex" ");"
.SH "DESCRIPTION"
.PP
Assign the latest material a texture referenced by the index tex\&. Of course, you will have pushed this texture with s3d_push_texture()
