.TH "s3d_pep_materials_a" "3" 
.SH "NAME" 
s3d_pep_materials_a \(em  
.SH "SYNOPSIS" 
.PP 
.nf 
#include <s3d.h> 
.sp 1 
\fBint \fBs3d_pep_materials_a\fP\fR( 
\fB	int \fBobject\fR\fR, 
\fB	const float *\fBmbuf\fR\fR, 
\fB	uint16_t \fBn\fR\fR); 
.fi 
.SH "Description" 
.PP 
Alters the last n pushed Materials. See s3d_push_materials_a() for more information how mbuf should look like. Use s3d_pep_material_a() if you only want to alter the latest material.          
.\" created by instant / docbook-to-man
