.TH "s3d_clone_target" "3" 
.SH "NAME" 
s3d_clone_target \(em  
.SH "SYNOPSIS" 
.PP 
.nf 
#include <s3d.h> 
.sp 1 
\fBint \fBs3d_clone_target\fP\fR( 
\fB	int \fBoid\fR\fR, 
\fB	int \fBtoid\fR\fR); 
.fi 
.SH "Description" 
.PP 
Changes the clone target of oid to another object (toid). This assumes you've got oid from s3d_clone before.          
.\" created by instant / docbook-to-man
