.TH "s3d_scale" "3" 
.SH "NAME" 
s3d_scale \(em  
.SH "SYNOPSIS" 
.PP 
.nf 
#include <s3d.h> 
.sp 1 
\fBint \fBs3d_scale\fP\fR( 
\fB	int \fBobject\fR\fR, 
\fB	float \fBs\fR\fR); 
.fi 
.SH "Description" 
.PP 
Scales the object. about factor s. s=1 will be the original size, \-1 will mirror it. 
.PP 
.RS 
\fBWarning:   
.PP 
s=0 is forbidden and will be ignored! s3d_scale is also absolute, not relative!  
 
.RE 
.\" created by instant / docbook-to-man, Mon 01 Sep 2008, 20:31 
