.TH "s3d_mcp_focus" "3" 
.SH "NAME" 
s3d_mcp_focus \(em  
.SH "SYNOPSIS" 
.PP 
.nf 
#include <s3d.h> 
.sp 1 
\fBint \fBs3d_mcp_focus\fP\fR( 
\fB	int \fBobject\fR\fR); 
.fi 
.SH "Description" 
.PP 
This is an mcp-only function. It gives focus (for receiving key-strokes etc.) to an app referenced by it's mcp-object-id.          
.\" created by instant / docbook-to-man
