.TH "s3d_ignore_callback" "3" 
.SH "NAME" 
s3d_ignore_callback \(em ignores an event 
.SH "SYNOPSIS" 
.PP 
.nf 
#include <s3d.h> 
.sp 1 
\fBvoid \fBs3d_ignore_callback\fP\fR( 
\fB	uint8_t \fBevent\fR\fR); 
.fi 
.SH "Description" 
.PP 
Sets the callback on ignore, that means it won't be queued up for later use. An incoming event of this type will simply be skipped.          
.\" created by instant / docbook-to-man
