.\"     Title: s3d_load_texture
.\"    Author:
.\" Generator: DocBook XSL Stylesheets
.\"
.\"    Manual:
.\"    Source:
.\"
.TH "S3D_LOAD_TEXTURE" "3" "" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
s3d_load_texture \- load texture from memory
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <s3d\&.h>
.fi
.ft
.HP 21
.BI "int s3d_load_texture(int\ " "object" ", uint32_t\ " "tex" ", uint16_t\ " "xpos" ", uint16_t\ " "ypos" ", uint16_t\ " "w" ", uint16_t\ " "h" ", const\ uint8_t\ *" "data" ");"
.SH "DESCRIPTION"
.PP
This will load an 32bit rgba image supplied in data at position xpos,ypos of the texture tex\&. The image has the width w and height h\&. This can be used to update only parts of the texture\&. It\'s no problem to supply big textures, as the image will be sent to server in fragments\&. Of course, you will have created the texture with s3d_push_texture, have an material assigned to the texture with s3d_pep_material_texture() and have your polygons set sane polygon texture coords using s3d_pep_polygon_tex_coord()\&.
