.TH "s3d_flags_off" "3" 
.SH "NAME" 
s3d_flags_off \(em disable flags of object 
.SH "SYNOPSIS" 
.PP 
.nf 
#include <s3d.h> 
.sp 1 
\fBint \fBs3d_flags_off\fP\fR( 
\fB	int \fBobject\fR\fR, 
\fB	uint32_t \fBflags\fR\fR); 
.fi 
.SH "Description" 
.PP 
turn some flags off for object.          
.\" created by instant / docbook-to-man
