.TH "s3dw_textbox_new" "3" 
.SH "NAME" 
s3dw_textbox_new \(em create a new textbox in the surface 
.SH "SYNOPSIS" 
.PP 
.nf 
#include <s3dw.h> 
.sp 1 
\fBs3dw_textbox * \fBs3dw_textbox_new\fP\fR( 
\fB	const s3dw_surface *\fBsurface\fR\fR, 
\fB	const char *\fBtext\fR\fR, 
\fB	float \fBposx\fR\fR, 
\fB	float \fBposy\fR\fR, 
\fB	float \fBwidth\fR\fR, 
\fB	float \fBheight\fR\fR); 
.fi 
.SH "Description" 
.PP 
Creates a new textbox on the surface, with "text" written on it and the upper left corner at (posx,posy) on the surface. Width and height define the size of the textbox including scrollbars which are rendered around the textfield. 
.PP 
See s3dw_textbox for information about callbacks which may be defined.          
.\" created by instant / docbook-to-man
