.TH "s3dw_surface_new" "3" 
.SH "NAME" 
s3dw_surface_new \(em create a new surface 
.SH "SYNOPSIS" 
.PP 
.nf 
#include <s3dw.h> 
.sp 1 
\fBs3dw_surface * \fBs3dw_surface_new\fP\fR( 
\fB	const char *\fBtitle\fR\fR, 
\fB	float \fBwidth\fR\fR, 
\fB	float \fBheight\fR\fR); 
.fi 
.SH "Description" 
.PP 
Creates a new surface (a new window) with title "title" and dimension "width" x "height". 
.PP 
See s3dw_surface for information about callbacks which may be defined.          
.\" created by instant / docbook-to-man
