.TH "s3dw_textbox_change_text" "3" 
.SH "NAME" 
s3dw_textbox_change_text \(em  
.SH "SYNOPSIS" 
.PP 
.nf 
#include <s3dw.h> 
.sp 1 
\fBvoid \fBs3dw_textbox_change_text\fP\fR( 
\fB	s3dw_textbox *\fBtextbox\fR\fR, 
\fB	const char *\fBtext\fR\fR); 
.fi 
.SH "Description" 
.PP 
Change the text in the referenced textbox to the specified text.          
.\" created by instant / docbook-to-man
