.TH "s3dw_input_gettext" "3" 
.SH "NAME" 
s3dw_input_gettext \(em  
.SH "SYNOPSIS" 
.PP 
.nf 
#include <s3dw.h> 
.sp 1 
\fBchar * \fBs3dw_input_gettext\fP\fR( 
\fB	s3dw_input *\fBinput\fR\fR); 
.fi 
.SH "Description" 
.PP 
Returns the text which is currently entered in the referenced input-box.          
.\" created by instant / docbook-to-man
