.TH "s3dw_textbox_scrollto" "3" 
.SH "NAME" 
s3dw_textbox_scrollto \(em scroll text to position 
.SH "SYNOPSIS" 
.PP 
.nf 
#include <s3dw.h> 
.sp 1 
\fBvoid \fBs3dw_textbox_scrollto\fP\fR( 
\fB	s3dw_textbox *\fBtextbox\fR\fR, 
\fB	int \fBx\fR\fR, 
\fB	int \fBy\fR\fR); 
.fi 
.SH "Description" 
.PP 
Scrolls the text in the textbox so that the character in row y, column x is in the top left corner of the textbox.          
.\" created by instant / docbook-to-man
