'\" t
.\"     Title: s3dw_handle_key
.\"    Author: Simon Wunderlich
.\" Generator: DocBook XSL Stylesheets
.\"
.\"    Manual: s3d Manual
.\"    Source: s3d
.\"  Language: English
.\"
.TH "S3DW_HANDLE_KEY" "3" "" "s3d" "s3d Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
s3dw_handle_key \- handle key input on widget
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <s3dw\&.h>
.fi
.ft
.HP \w'int\ s3dw_handle_key('u
.BI "int s3dw_handle_key(const\ struct\ s3d_evt\ *" "event" ");"
.SH "DESCRIPTION"
.PP
This is somehow useful to call in your keyhandler functions if you want to have input\-boxes work\&. ;)
.sp
.if n \{\
.RS 4
.\}
.nf
 // way 1:
 s3d_set_callback(S3D_EVENT_KEY,s3dw_handle_key);

 // way 2:
 \&.\&.\&.
 void key(struct s3d_evt *evt)
 {
         s3dw_handle_key(evt);
         \&.\&.\&.\&.
         // your own keyhandler code
         \&.\&.\&.
 }
 \&.\&.\&.\&.
 s3d_set_callback(S3D_EVENT_KEY,key);
.fi
.if n \{\
.RE
.\}
.SH "AUTHOR"
.PP
\fBSimon Wunderlich\fR
.RS 4
Author of s3d
.RE
