.TH "s3dw_moveit" "3" 
.SH "NAME" 
s3dw_moveit \(em  
.SH "SYNOPSIS" 
.PP 
.nf 
#include <s3dw.h> 
.sp 1 
\fBvoid \fBs3dw_moveit\fP\fR( 
\fB	s3dw_widget *\fBwidget\fR\fR); 
.fi 
.SH "Description" 
.PP 
Moves/translates the widget as you specified in it's private s3dw_widget structure. Should be casted with S3DWIDGET().          
.\" created by instant / docbook-to-man
