.TH "s3dw_label_new" "3" 
.SH "NAME" 
s3dw_label_new \(em create a new label in the surface 
.SH "SYNOPSIS" 
.PP 
.nf 
#include <s3dw.h> 
.sp 1 
\fBs3dw_label * \fBs3dw_label_new\fP\fR( 
\fB	const s3dw_surface *\fBsurface\fR\fR, 
\fB	const char *\fBtext\fR\fR, 
\fB	float \fBposx\fR\fR, 
\fB	float \fBposy\fR\fR); 
.fi 
.SH "Description" 
.PP 
Creates a new label on the surface, with "text" written on it and the upper left corner at (posx,posy) on the surface. 
.PP 
See s3dw_label for information about callbacks which may be defined.          
.\" created by instant / docbook-to-man
