.TH "s3dw_textbox_scrolldown" "3" 
.SH "NAME" 
s3dw_textbox_scrolldown \(em  
.SH "SYNOPSIS" 
.PP 
.nf 
#include <s3dw.h> 
.sp 1 
\fBvoid \fBs3dw_textbox_scrolldown\fP\fR( 
\fB	s3dw_textbox *\fBtextbox\fR\fR); 
.fi 
.SH "Description" 
.PP 
Scrolls the text in the textbox down by one line, if possible.          
.\" created by instant / docbook-to-man
