'\" t
.\"     Title: s3dw_moveit
.\"    Author: Simon Wunderlich
.\" Generator: DocBook XSL Stylesheets
.\"
.\"    Manual: s3d Manual
.\"    Source: s3d
.\"  Language: English
.\"
.TH "S3DW_MOVEIT" "3" "" "s3d" "s3d Manual"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
s3dw_moveit \- apply widgets moving function
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <s3dw\&.h>
.fi
.ft
.HP \w'void\ s3dw_moveit('u
.BI "void s3dw_moveit(s3dw_widget\ *" "widget" ");"
.SH "DESCRIPTION"
.PP
Moves/translates the widget as you specified in it\'s private s3dw_widget structure\&. Should be casted with S3DWIDGET()\&.
.SH "AUTHOR"
.PP
\fBSimon Wunderlich\fR
.RS 4
Author of s3d
.RE
