.\"     Title: s3dw_input_change_text
.\"    Author:
.\" Generator: DocBook XSL Stylesheets
.\"
.\"    Manual:
.\"    Source:
.\"
.TH "S3DW_INPUT_CHANGE_TE" "3" "" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
s3dw_input_change_text \- changes the text of the input
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <s3dw\&.h>
.fi
.ft
.HP 28
.BI "void s3dw_input_change_text(s3dw_input\ *" "input" ", const\ char\ *" "text" ");"
.SH "DESCRIPTION"
.PP
Change the text in the referenced input\-box to the specified text\&.
