.TH "s3dw_delete" "3" 
.SH "NAME" 
s3dw_delete \(em delete widget 
.SH "SYNOPSIS" 
.PP 
.nf 
#include <s3dw.h> 
.sp 1 
\fBvoid \fBs3dw_delete\fP\fR( 
\fB	s3dw_widget *\fBwidget\fR\fR); 
.fi 
.SH "Description" 
.PP 
Deletes any widget. Should be casted with S3DWIDGET().          
.\" created by instant / docbook-to-man
