.TH "s3dw_object_info" "3" 
.SH "NAME" 
s3dw_object_info \(em  
.SH "SYNOPSIS" 
.PP 
.nf 
#include <s3dw.h> 
.sp 1 
\fBint \fBs3dw_object_info\fP\fR( 
\fB	struct s3d_evt *\fBevent\fR\fR); 
.fi 
.SH "Description" 
.PP 
This can be used to let s3dw handle S3D_EVENT_OBJ_INFO-events. With this, s3dw can consider the camera position and makes things like following the camera possible.          
.\" created by instant / docbook-to-man
