'\" t
.\"     Title: dot_mcp
.\"    Author: Simon Wunderlich
.\" Generator: DocBook XSL Stylesheets
.\"
.\"    Manual: s3d Manual
.\"    Source: s3d
.\"  Language: English
.\"
.TH "DOT_MCP" "1" "" "s3d" "s3d Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
dot_mcp \- mcp for s3d
.SH "SYNOPSIS"
.HP \w'\fBdot_mcp\fR\ 'u
\fBdot_mcp\fR [\-\-s3d\-url\ \fIurl\fR]
.SH "OPTIONS"
.PP
This program follows the usual
GNU
command line syntax\&. A summary of the options supported by
\fBdot_mcp\fR
is below\&.
.PP
\fB\-\-s3d\-url \fR\fB\fIurl\fR\fR
.RS 4
skip S3D environment and connect to this url
.RE
.SH "DESCRIPTION"
.PP

\fBdot_mcp(1)\fR
is a mcp (which is the window manager in s3d\-terms) for s3d\&.
.PP
.SH "SEE ALSO"
.PP
\fBs3d\fR(1)\&.
.PP

\m[blue]\fBs3d project page on berlios\fR\m[]\&\s-2\u[1]\d\s+2
.SH "AUTHOR"
.PP
\fBSimon Wunderlich\fR
.RS 4
Author of s3d
.RE
.SH "NOTES"
.IP " 1." 4
s3d project page on berlios
.RS 4
\%http://s3d.berlios.de/
.RE
