.\"     Title: dot_mcp
.\"    Author:
.\" Generator: DocBook XSL Stylesheets
.\"
.\"    Manual:
.\"    Source:
.\"
.TH "DOT_MCP" "1" "" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
dot_mcp \- mcp for s3d
.SH "SYNOPSIS"
.HP 8
\fBdot_mcp\fR [\-\-s3d\-url\ \fIurl\fR]
.SH "OPTIONS"
.PP
This program follows the usual
GNU
command line syntax\&. A summary of the options supported by
\fBdot_mcp\fR
is below\&.
.PP
\fB\-\-s3d\-url \fR\fB\fIurl\fR\fR
.RS 4
skip S3D environment and connect to this url
.RE
.SH "DESCRIPTION"
.PP

\fBdot_mcp(1)\fR
is a mcp (which is the window manager in s3d\-terms) for s3d\&.
.PP
.SH "SEE ALSO"
.PP
\fBs3d\fR(1)\&.
.PP

\fI s3d project page on berlios \fR\&[1]
.SH "NOTES"
.IP " 1." 4
s3d project page on berlios
.RS 4
\%http://s3d.berlios.de/
.RE
