.\"     Title: kism3d
.\"    Author:
.\" Generator: DocBook XSL Stylesheets
.\"
.\"    Manual:
.\"    Source:
.\"
.TH "KISM3D" "1" "" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
kism3d \- 802.11 visualizer for s3d
.SH "SYNOPSIS"
.HP 7
\fBkism3d\fR [\-\-s3d\-url\ \fIurl\fR] \fIHOST\fR:\fIPORT\fR
.SH "DESCRIPTION"
.PP

\fBkism3d(1)\fR
is a 3D 802\&.11 visualizer for kismet\&.
.PP
.SH "OPTIONS"
.PP
This program follows the usual
GNU
command line syntax\&. A summary of the options supported by
\fBkism3d\fR
is below\&.
.PP
\fB\-\-s3d\-url \fR\fB\fIurl\fR\fR
.RS 4
skip S3D environment and connect to this url
.RE
.SH "SEE ALSO"
.PP

\fBs3d\fR(1),
\fBkismet\fR(1)\&.
.PP

\fI s3d project page on berlios \fR\&[1]
.SH "NOTES"
.IP " 1." 4
s3d project page on berlios
.RS 4
\%http://s3d.berlios.de/
.RE
