'\" t
.\"     Title: s3d
.\"    Author: Simon Wunderlich
.\" Generator: DocBook XSL Stylesheets
.\"
.\"    Manual: s3d Manual
.\"    Source: s3d
.\"  Language: English
.\"
.TH "S3D" "1" "" "s3d" "s3d Manual"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
s3d \- network display server
.SH "SYNOPSIS"
.HP \w'\fBs3d\fR\ 'u
\fBs3d\fR [\-s|\-\-use\-sdl] [\-r|\-\-rc\ \fIrc\-script\fR] [\-n|\-\-no\-rc]
.SH "DESCRIPTION"
.PP

\fBs3d(1)\fR
is a network display server which can be used as 3d desktop environment\&.
.PP
.SH "OPTIONS"
.PP
This program follows the usual
GNU
command line syntax\&. A summary of the options supported by
\fBs3d\fR
is below\&.
.PP
\fB\-s\fR, \fB\-\-use\-sdl\fR
.RS 4
Tells s3d to use SDL as graphics framework system\&.
.RE
.PP
\fB\-r \fR\fB\fIrc\-script\fR\fR, \fB\-\-rc \fR\fB\fIrc\-script\fR\fR
.RS 4
Use the specified file as rc\-script\&. By default s3d uses ~/\&.s3drc as per\-user rc\-script and /etc/s3drc as system\-wide rc\-script
.RE
.PP
\fB\-n\fR, \fB\-\-no\-rc\fR
.RS 4
Don\'t use rc\-scripts even if the exist in the apropriate locations\&.
.RE
.SH "SEE ALSO"
.PP

\m[blue]\fB s3d project page on berlios \fR\m[]\&\s-2\u[1]\d\s+2
.SH "AUTHOR"
.PP
This manual page was written by Timo Schneider
timo\&.schneider@s2004\&.tu\-chemnitz\&.de
for the
Debian(TM)
project (but may be used by others)\&.
.SH "AUTHOR"
.PP
\fBSimon Wunderlich\fR
.RS 4
Author of s3d
.RE
.SH "NOTES"
.IP " 1." 4
s3d project page on berlios
.RS 4
\%http://s3d.berlios.de/
.RE
