.\"     Title: s3dosm
.\"    Author:
.\" Generator: DocBook XSL Stylesheets
.\"
.\"    Manual:
.\"    Source:
.\"
.TH "S3DOSM" "1" "" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
s3dosm \- gps card application for s3d
.SH "SYNOPSIS"
.HP 7
\fBs3dosm\fR [\-o|\-\-osm\ \fIMINLAT\fR,\fIMINLON\fR,\fIMAXLAT\fR,\fIMAXLON\fR] [\-h|\-\-help] [\-\-s3d\-url\ \fIurl\fR] [\fIfiles\fR]
.SH "DESCRIPTION"
.PP

\fBs3dosm(1)\fR
is a 3D gps card application for openstreetmap/kismet xml card data\&.
.PP
.SH "OPTIONS"
.PP
This program follows the usual
GNU
command line syntax\&. A summary of the options supported by
\fBs3dosm\fR
is below\&.
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Show summary of options and exit\&.
.RE
.PP
\fB\-o\fR, \fB\-\-osm\fR \fIMINLAT\fR,\fIMINLON\fR,\fIMAXLAT\fR,\fIMAXLON\fR
.RS 4
Load a map with the given bounding box from the openstreetmap server\&.
.RE
.PP
\fB\-\-s3d\-url \fR\fB\fIurl\fR\fR
.RS 4
skip S3D environment and connect to this url
.RE
.SH "EXAMPLES"
.PP

.sp
.RS 4
.nf
$ \fBs3osm \-\-osm \fR\fB\fI12\&.90142,50\&.82475,12\&.93352,50\&.84592\fR\fR

$ \fBs3osm \fR\fB\fIosmdata\fR\fR\fB\&.xml\fR
.fi
.RE
.sp
.SH "SEE ALSO"
.PP

\fBs3d\fR(1)\&.
.PP

\fI s3d project page on berlios \fR\&[1]
.SH "NOTES"
.IP " 1." 4
s3d project page on berlios
.RS 4
\%http://s3d.berlios.de/
.RE
