.\"     Title: s3dvt
.\"    Author:
.\" Generator: DocBook XSL Stylesheets
.\"
.\"    Manual:
.\"    Source:
.\"
.TH "S3DVT" "1" "" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
s3dvt \- 3d terminal emulator for s3d
.SH "SYNOPSIS"
.HP 6
\fBs3dvt\fR [\-h|\-\-help] [\-\-s3d\-url\ \fIurl\fR]
.SH "DESCRIPTION"
.PP

\fBs3dvt(1)\fR
is a terminal emulator\&.
.PP
.SH "OPTIONS"
.PP
This program follows the usual
GNU
command line syntax\&. A summary of the options supported by
\fBs3dvt\fR
is below\&.
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Show summary of options and exit\&.
.RE
.PP
\fB\-\-s3d\-url \fR\fB\fIurl\fR\fR
.RS 4
skip S3D environment and connect to this url
.RE
.SH "SEE ALSO"
.PP

\fBs3d\fR(1)\&.
.PP

\fI s3d project page on berlios \fR\&[1]
.SH "NOTES"
.IP " 1." 4
s3d project page on berlios
.RS 4
\%http://s3d.berlios.de/
.RE
