'\" t
.\"     Title: s3dvt
.\"    Author: Simon Wunderlich
.\" Generator: DocBook XSL Stylesheets
.\"
.\"    Manual: s3d Manual
.\"    Source: s3d
.\"  Language: English
.\"
.TH "S3DVT" "1" "" "s3d" "s3d Manual"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
s3dvt \- 3d terminal emulator for s3d
.SH "SYNOPSIS"
.HP \w'\fBs3dvt\fR\ 'u
\fBs3dvt\fR [\-h|\-\-help] [\-\-s3d\-url\ \fIurl\fR]
.SH "DESCRIPTION"
.PP

\fBs3dvt(1)\fR
is a terminal emulator\&.
.PP
.SH "OPTIONS"
.PP
This program follows the usual
GNU
command line syntax\&. A summary of the options supported by
\fBs3dvt\fR
is below\&.
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Show summary of options and exit\&.
.RE
.PP
\fB\-\-s3d\-url \fR\fB\fIurl\fR\fR
.RS 4
skip S3D environment and connect to this url
.RE
.SH "SEE ALSO"
.PP

\fBs3d\fR(1)\&.
.PP

\m[blue]\fB s3d project page on berlios \fR\m[]\&\s-2\u[1]\d\s+2
.SH "AUTHOR"
.PP
\fBSimon Wunderlich\fR
.RS 4
Author of s3d
.RE
.SH "NOTES"
.IP " 1." 4
s3d project page on berlios
.RS 4
\%http://s3d.berlios.de/
.RE
