.TH "s3d_key_event" "9" 
.SH "NAME" 
struct s3d_key_event \(em  
.SH "SYNOPSIS" 
.PP 
.nf 
#include <s3d.h> 
.fi 
.SH "Structure Members" 
.PP 
.nf 
struct s3d_key_event { 
uint16_t keysym; 
uint16_t unicode; 
uint16_t modifier; 
uint16_t state; 
} 
.fi 
.PP 
.SH "Description" 
.\" created by instant / docbook-to-man
