.TH "s3d_but_info" "9" 
.SH "NAME" 
struct s3d_but_info \(em  
.SH "SYNOPSIS" 
.PP 
.nf 
#include <s3d.h> 
.fi 
.SH "Structure Members" 
.PP 
.nf 
struct s3d_but_info { 
uint8_t button; 
uint8_t state; 
} 
.fi 
.PP 
.SH "Description" 
.PP 
Can be used on the buffer of an event of type S3D_EVENT_MBUTTON.      
.\" created by instant / docbook-to-man
