'\" t
.\"     Title: s3d_evt
.\"    Author: Simon Wunderlich
.\" Generator: DocBook XSL Stylesheets
.\"
.\"    Manual: s3d Manual
.\"    Source: s3d
.\"  Language: English
.\"
.TH "S3D_EVT" "9" "" "s3d" "s3d Manual"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
s3d_evt
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <s3d\&.h>
.fi
.ft
.SH "STRUCTURE MEMBERS"
.sp
.if n \{\
.RS 4
.\}
.nf
struct s3d_evt {
	uint8_t event;
	int length;
	char *buf;
	struct s3d_evt *next;
}
.fi
.if n \{\
.RE
.\}
.SH "DESCRIPTION"
.PP
This is the event information holder\&.
.PP
event
.RS 4
gives the event type
.RE
.PP
length
.RS 4
gives the length of the buffer *buf
.RE
.PP
buf
.RS 4
is the pointer to the multiple purpose buffer, which will have more specific information about the object
.RE
.PP
next
.RS 4
can be safely ignored ;)
.RE
.SH "AUTHOR"
.PP
\fBSimon Wunderlich\fR
.RS 4
Author of s3d
.RE
