'\" t
.\"     Title: s3d_but_info
.\"    Author: Simon Wunderlich
.\" Generator: DocBook XSL Stylesheets
.\"
.\"    Manual: s3d Manual
.\"    Source: s3d
.\"  Language: English
.\"
.TH "S3D_BUT_INFO" "9" "" "s3d" "s3d Manual"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
s3d_but_info \- status of a button
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <s3d\&.h>
.fi
.ft
.SH "STRUCTURE MEMBERS"
.sp
.if n \{\
.RS 4
.\}
.nf
struct s3d_but_info {
	uint8_t button;
	uint8_t state;
}
.fi
.if n \{\
.RE
.\}
.SH "DESCRIPTION"
.PP
Can be used on the buffer of an event of type S3D_EVENT_MBUTTON\&.
.SH "AUTHOR"
.PP
\fBSimon Wunderlich\fR
.RS 4
Author of s3d
.RE
