'\" t
.\"     Title: _s3dw_widget
.\"    Author: Simon Wunderlich
.\" Generator: DocBook XSL Stylesheets
.\"
.\"    Manual: s3d Manual
.\"    Source: s3d
.\"  Language: English
.\"
.TH "_S3DW_WIDGET" "9" "" "s3d" "s3d Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
s3dw_widget \- s3d widget information
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <s3dw\&.h>
.fi
.ft
.SH "STRUCTURE MEMBERS"
.sp
.if n \{\
.RS 4
.\}
.nf
struct _s3dw_widget {
	int type;
	s3dw_widget *parent;
	s3dw_style *style;
	int nobj;
	s3dw_widget **pobj;
	int focus;
	int flags;
	float ax;
	float ay;
	float az;
	float as;
	float arx;
	float ary;
	float arz;
	float width;
	float height;
	uint32_t oid;
	void *ptr;
	float x;
	float y;
	float z;
	float s;
	float rx;
	float ry;
	float rz;
}
.fi
.if n \{\
.RE
.\}
.SH "DESCRIPTION"
.PP
This is the most basic widget type, it contains all the "general" widget information\&. If you want to move a widget, you\*(Aqd change x,y,z,s and rx,ry,rz and call s3dw_moveit to turn your action reality\&. Every other widget has this type as first entry, so a simple typecast to s3dw_widget will give you the widgets "general" information\&. For typecast, you may use S3DWIDGET()\&.
.PP
The pointer ptr allows linking to user\-specific data structures\&. That comes in handy if the widget is called back by an event, and the program must now find out on which data the user reacted\&.
.SH "AUTHOR"
.PP
\fBSimon Wunderlich\fR
.RS 4
Author of s3d
.RE
