.TH "_s3dw_input" "9" 
.SH "NAME" 
struct _s3dw_input \(em  
.SH "SYNOPSIS" 
.PP 
.nf 
#include <s3dw.h> 
.fi 
.SH "Structure Members" 
.PP 
.nf 
struct _s3dw_input { 
s3dw_widget widget; 
char *text; 
uint32_t oid_text; 
s3dw_callback onclick; 
s3dw_callback onedit; 
} 
.fi 
.PP 
.SH "Description" 
.PP 
The inputs is an input-field where a user may type things. onclick reacts on click in the field, onedit notifies you when someone writes in the field.      
.\" created by instant / docbook-to-man
