'\" t
.\"     Title: _s3dw_style
.\"    Author: Simon Wunderlich
.\" Generator: DocBook XSL Stylesheets
.\"
.\"    Manual: s3d Manual
.\"    Source: s3d
.\"  Language: English
.\"
.TH "_S3DW_STYLE" "9" "" "s3d" "s3d Manual"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
s3dw_style
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <s3dw\&.h>
.fi
.ft
.SH "STRUCTURE MEMBERS"
.sp
.if n \{\
.RS 4
.\}
.nf
struct _s3dw_style {
	char *name;
	char *fontface;
	float surface_mat;
	float input_mat;
	float inputback_mat;
	float text_mat;
	float title_mat;
	float title_text_mat;
}
.fi
.if n \{\
.RE
.\}
.SH "DESCRIPTION"
.PP
With s3dw_style you can change the colors/materials of your widgets\&. materials are in the same as in s3d_push_materials_a, that means red,green,blue and alpha float values (between 0\&.0 and 1\&.0) for ambience, specular and diffuse color\&.
.PP
name
.RS 4
name of the style \&.\&.\&. kind of redundant
.RE
.PP
fontface
.RS 4
font face for all used fonts
.RE
.PP
surface_mat
.RS 4
material for the surface background
.RE
.PP
input_mat
.RS 4
material for button boxes and other widgets
.RE
.PP
inputback_mat
.RS 4
material for input field background
.RE
.PP
text_mat
.RS 4
material for the text on buttons and inputs
.RE
.PP
title_mat
.RS 4
material for the title bar
.RE
.PP
title_text_mat
.RS 4
material for the text on the title bar
.RE
.SH "AUTHOR"
.PP
\fBSimon Wunderlich\fR
.RS 4
Author of s3d
.RE
