.TH "_s3dw_surface" "9" 
.SH "NAME" 
struct _s3dw_surface \(em  
.SH "SYNOPSIS" 
.PP 
.nf 
#include <s3dw.h> 
.fi 
.SH "Structure Members" 
.PP 
.nf 
struct _s3dw_surface { 
s3dw_widget widget; 
uint32_t oid_title; 
uint32_t oid_tbar; 
char *title; 
} 
.fi 
.PP 
.SH "Description" 
.PP 
A surface is the window of this widget library, holding all of our elements like buttons, inputfields etc ...      
.\" created by instant / docbook-to-man, Mon 01 Sep 2008, 20:31 
